dir: &dir log/mmd_feature
n_steps: &n_steps 1000 #0
every: &every 25
seed: null
device: &device 'cuda'
total_n: &total_n 10000
batch_size: &batch_size 2000
data_batch_size: 100

weight_step: &weight_step 1 #0.01
step_size: &step_size 0.1
name: &name mlp_mmd
burn_in_steps: &burn_in_steps 0. #500.
start_sample: &start_sample 0.
sub_dir: &sub_dir mlp
suffix: *step_size

kernel: &kernel GaussianKernel
dis_emb: &dis_emb False