dir: &dir log/dumb_feature
n_steps: &n_steps 1000 #500
every: &every 50
seed: null
sweet_init: &sweet_init false

device: &device 'cuda'
total_n: &total_n 10000 #0
batch_size: &batch_size 2000


data_batch_size: *batch_size
weight_step: &weight_step 0.0 #0.01
step_size: &step_size 0.1 #0.01
name: &name mlp_dumb
burn_in_steps: &burn_in_steps 0.
start_sample: &start_sample 0. #10
sub_dir: &sub_dir mlp # dcgan
suffix: *step_size
